import type {
  MetricKey,
  MetricMeta,
  BreakdownDimension,
  ChartType,
  OrgMetricKey,
} from "@/types/widget";

/**
 * Central registry of all chartable metrics.
 *
 * Each entry describes a metric the widget system can display:
 * label, category (for modal grouping), compatible chart types,
 * valid breakdown dimensions, formatter, and default color.
 *
 * Adding a metric = one entry here + one entry in the backend METRIC_REGISTRY.
 */
export const METRIC_REGISTRY: Record<MetricKey, MetricMeta> = {
  // ── Usage ──────────────────────────────────────────────
  run_count: {
    key: "run_count",
    label: "Run Count",
    description: "Total agent executions in the selected period",
    tooltip: "Counts every agent run regardless of outcome (success, failure, or error). Each invocation of an agent workflow is counted once. Use breakdowns to compare activity across teams, projects, or models.",
    category: "Usage",
    defaultChartType: "area",
    compatibleChartTypes: ["line", "area", "bar", "kpi", "table"],
    format: "number",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#6366f1",
  },
  active_users: {
    key: "active_users",
    label: "Active Users",
    description: "Unique users who triggered at least one agent run",
    tooltip: "Counts distinct user IDs that initiated at least one agent run in the period. A user who runs 50 agents still counts as one active user. Useful for tracking adoption and seat utilization.",
    category: "Usage",
    defaultChartType: "area",
    compatibleChartTypes: ["line", "area", "bar", "kpi", "table"],
    format: "number",
    validBreakdowns: ["team", "project"],
    color: "#8b5cf6",
  },

  // ── Cost ───────────────────────────────────────────────
  cost: {
    key: "cost",
    label: "Cost (USD)",
    description: "Total spend across all agent runs",
    tooltip: "Sum of all LLM API charges (input + output tokens) for every agent run. Does not include infrastructure or compute costs. Break down by model to identify the most expensive providers.",
    category: "Cost",
    defaultChartType: "area",
    compatibleChartTypes: ["line", "area", "bar", "kpi", "pie", "table", "gauge"],
    format: "currency",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#10b981",
  },
  cost_per_run: {
    key: "cost_per_run",
    label: "Cost Per Run",
    description: "Average cost for each agent execution",
    tooltip: "Total cost divided by the number of runs. Includes all runs regardless of outcome. A rising cost-per-run may indicate longer conversations, more expensive models, or increased tool usage per run.",
    category: "Cost",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "bar", "kpi"],
    format: "currency",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#059669",
  },
  tokens_input: {
    key: "tokens_input",
    label: "Input Tokens",
    description: "Total input tokens consumed by all runs",
    tooltip: "Sum of prompt tokens sent to LLMs across all runs. Includes system prompts, user messages, and tool call context. High input token counts often correlate with longer conversation histories or large context windows.",
    category: "Cost",
    defaultChartType: "area",
    compatibleChartTypes: ["line", "area", "bar", "kpi", "table"],
    format: "number",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#14b8a6",
  },
  tokens_output: {
    key: "tokens_output",
    label: "Output Tokens",
    description: "Total output tokens generated by all runs",
    tooltip: "Sum of completion tokens generated by LLMs across all runs. Output tokens are typically more expensive than input tokens. Compare with input tokens to understand the response-to-prompt ratio.",
    category: "Cost",
    defaultChartType: "area",
    compatibleChartTypes: ["line", "area", "bar", "kpi", "table"],
    format: "number",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#0d9488",
  },

  // ── Performance ────────────────────────────────────────
  success_rate: {
    key: "success_rate",
    label: "Success Rate",
    description: "Percentage of runs that completed successfully",
    tooltip: "Percentage of runs that finished without errors or failures. Calculated as successful runs divided by total runs. A sustained drop may indicate model degradation, prompt issues, or upstream service problems.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "kpi"],
    format: "percent",
    validBreakdowns: ["team", "project", "agent_type"],
    color: "#10b981",
  },
  failure_rate: {
    key: "failure_rate",
    label: "Failure Rate",
    description: "Percentage of runs that ended in failure",
    tooltip: "Percentage of runs that terminated with a failure status. Failures include timeouts, unhandled exceptions, and explicit abort signals. This is the inverse complement of success rate minus error rate.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "kpi"],
    format: "percent",
    validBreakdowns: ["team", "project", "agent_type"],
    color: "#ef4444",
  },
  error_rate: {
    key: "error_rate",
    label: "Error Rate",
    description: "Percentage of runs that produced a categorized error",
    tooltip: "Percentage of runs that ended with a classified error (rate limit, auth failure, context overflow, etc.). Break down by error category to identify the most common failure modes and prioritize fixes.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "bar", "kpi", "pie", "table"],
    format: "percent",
    validBreakdowns: ["team", "project", "agent_type", "error_category"],
    color: "#f59e0b",
  },
  latency_p50: {
    key: "latency_p50",
    label: "Latency P50",
    description: "Median execution time across all runs",
    tooltip: "The median (50th percentile) wall-clock duration from run start to completion. Half of all runs finish faster than this value. Compare P50 with P95/P99 to understand the spread of execution times.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "kpi"],
    format: "duration",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#6366f1",
  },
  latency_p95: {
    key: "latency_p95",
    label: "Latency P95",
    description: "95th percentile execution time",
    tooltip: "The 95th percentile wall-clock duration. Only 5% of runs take longer than this. A large gap between P50 and P95 indicates high variance, possibly caused by retries, rate limiting, or complex agent workflows.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "kpi"],
    format: "duration",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#f59e0b",
  },
  latency_p99: {
    key: "latency_p99",
    label: "Latency P99",
    description: "99th percentile execution time",
    tooltip: "The 99th percentile wall-clock duration. Only 1% of runs take longer than this. Spikes in P99 often reveal outlier behaviors such as complex multi-step agent workflows, retry storms, or upstream provider degradation that P50/P95 may miss.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "kpi"],
    format: "duration",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#ef4444",
  },
  queue_wait_avg: {
    key: "queue_wait_avg",
    label: "Avg Queue Wait",
    description: "Average time runs spent waiting in queue",
    tooltip: "Mean time between a run being enqueued and execution starting. A rising average queue wait signals capacity constraints — consider scaling agent workers or adjusting concurrency limits. Compare with P95 to detect whether wait times are uniformly slow or driven by outliers.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "kpi", "table"],
    format: "duration",
    validBreakdowns: ["team", "project", "agent_type"],
    color: "#06b6d4",
  },
  queue_wait_p95: {
    key: "queue_wait_p95",
    label: "Queue Wait P95",
    description: "95th percentile queue wait time",
    tooltip: "The 95th percentile queue wait time. Only 5% of runs waited longer than this before execution started. A large gap between average and P95 queue wait suggests bursty traffic patterns or priority-queue imbalances.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "kpi"],
    format: "duration",
    validBreakdowns: ["team", "project", "agent_type"],
    color: "#f43f5e",
  },

  // ── User Feedback ───────────────────────────────────────
  approval_rate: {
    key: "approval_rate",
    label: "Approval Rate",
    description: "Percentage of rated runs that received positive feedback",
    tooltip: "Of all runs where a user left a rating (thumbs up/down), this shows the percentage that were positive. Only rated runs are counted — unrated runs are excluded. A declining approval rate may indicate degrading output quality even when success rate stays high.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "bar", "kpi"],
    format: "percent",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#22c55e",
  },
  rating_participation: {
    key: "rating_participation",
    label: "Rating Participation",
    description: "Percentage of completed runs that received a user rating",
    tooltip: "Shows what fraction of all runs were rated by users. Low participation means the approval rate metric is based on a small sample. Track this alongside approval rate to understand how representative the feedback signal is.",
    category: "Performance",
    defaultChartType: "line",
    compatibleChartTypes: ["line", "area", "bar", "kpi"],
    format: "percent",
    validBreakdowns: ["team", "project", "agent_type", "model"],
    color: "#a855f7",
  },
};

/** Metrics grouped by category, for the modal grouped dropdown. */
export const METRIC_BY_CATEGORY = Object.values(METRIC_REGISTRY).reduce(
  (acc, m) => {
    (acc[m.category] ??= []).push(m);
    return acc;
  },
  {} as Record<string, MetricMeta[]>,
);

/** Breakdown dimension labels for display. */
export const BREAKDOWN_LABELS: Record<BreakdownDimension, string> = {
  team: "Team",
  project: "Project",
  agent_type: "Agent Type",
  error_category: "Error Category",
  model: "Model",
};

/** Max allowed metrics per chart type. 0 = sealed (no user metrics). */
export const MAX_METRICS: Record<ChartType, number> = {
  line: 3,
  area: 3,
  bar: 1,
  pie: 1,
  kpi: 1,
  table: 5,
  gauge: 1,
  stat: 1,
  active_users_trend: 0,
  top_users: 0,
};

/** Chart type labels and whether users can create them from the modal. */
export const CHART_TYPE_META: Record<
  ChartType,
  { label: string; icon: string; userCreatable: boolean }
> = {
  line: { label: "Line", icon: "\u2571", userCreatable: true },
  area: { label: "Area", icon: "\u25B3", userCreatable: true },
  bar: { label: "Bar", icon: "\u2593", userCreatable: true },
  pie: { label: "Pie", icon: "\u25D4", userCreatable: true },
  kpi: { label: "KPI", icon: "#", userCreatable: true },
  table: { label: "Table", icon: "\u2261", userCreatable: true },
  gauge: { label: "Gauge", icon: "\u25D0", userCreatable: true },
  stat: { label: "Stat", icon: "\u00F7", userCreatable: true },
  active_users_trend: { label: "Active Users Trend", icon: "", userCreatable: false },
  top_users: { label: "Top Users", icon: "", userCreatable: false },
};

/** Org-level metric labels for display. */
export const ORG_METRIC_LABELS: Record<OrgMetricKey, string> = {
  monthly_budget: "Monthly Budget",
  licensed_users: "Licensed Users",
};

/** Whether a chart type requires an org metric. */
export function requiresOrgMetric(chartType: ChartType): boolean {
  return chartType === "gauge" || chartType === "stat";
}

/**
 * Whether a chart type requires, supports, or disallows a breakdown dimension.
 * - "required": must have a breakdown (pie)
 * - "optional": breakdown is allowed but not required (bar, table)
 * - "none": no breakdown dimension (line, area, kpi, gauge, stat, sealed)
 */
export function breakdownModeForChartType(
  chartType: ChartType,
): "required" | "optional" | "none" {
  switch (chartType) {
    case "pie":
      return "required";
    case "bar":
    case "table":
      return "optional";
    default:
      return "none";
  }
}
